[project]
name = "etl"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "certifi==2024.8.30",
    "charset-normalizer==3.4.0",
    "idna==3.10",
    "importlib_metadata==8.5.0",
    "psycopg2==2.9.10",
    "python-dotenv==1.0.1",
    "requests==2.32.3",
    "sqlparse==0.5.3",
    "tabulate==0.9.0",
    "urllib3==2.2.3",
    "yoyo-migrations==9.0.0",
    "zipp==3.21.0",
    "pep8-naming==0.14.1",
    "mccabe==0.7.0",
    "pytest==8.3.4",
    "black==25.1.0",
    "aiofiles>=24.1.0",
]

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/foo.py  # exclude a file named foo.py in the root of the project
'''
exclude = '''
/(
    \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
)/
'''
force-exclude = '''
^/examples/
'''

[tool.isort]
profile = "black"
multi_line_output = 3